"""add chunk source provenance

Revision ID: 8812ff7d578f
Revises: 
Create Date: 2026-09-25 00:48:59.532543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8812ff7d578f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('source_start_index', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_end_index', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_start_label', sa.String(length=128), nullable=True))
    op.add_column('document_chunks', sa.Column('source_end_label', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'source_end_label')
    op.drop_column('document_chunks', 'source_start_label')
    op.drop_column('document_chunks', 'source_end_index')
    op.drop_column('document_chunks', 'source_start_index')
    # ### end Alembic commands ###
